CI additions
drachtio/drachtio-server pull request #204
Opened 2022-05-18 14:16 UTC by ghenry

Nice and clean now. See #202.

2022-05-18 14:31 UTC, ghenry commented
This should be good to go now @davehorton

2022-05-18 14:46 UTC, davehorton commented
Thanks.  This looks like it will be helpful -- lots of issues to fix!

Before I merge the changes, I would like to understand how I will be able to run these tests locally on my laptop.  Can you give me some quick pointers?

2022-05-19 13:38 UTC, davehorton requested changes

2022-05-19 13:38 UTC, davehorton commented on .github/workflows/cppcheck.yml
> +  clang-analyzer:
Could you change this name to cpp-analyzer or something, so it doesn't collide with the other "clang-analyzer" job

2022-05-19 13:52 UTC, davehorton requested changes

2022-05-19 13:52 UTC, davehorton commented on .github/workflows/sonarcloud.yml
> +          sudo apt-get install -y libtool libtool-bin libcurl4-openssl-dev libpcap-dev
cmake needs to be added as a dependency

2022-05-19 14:01 UTC, davehorton commented on .github/workflows/sonarcloud.yml
> +          sudo apt-get install -y libtool libtool-bin libcurl4-openssl-dev libpcap-dev
scratch that, this is something I need to add in ci.yml.

2022-05-19 17:07 UTC, davehorton approved these changes

2022-05-19 17:34 UTC, merged