Enable building with system hiredis
drachtio/drachtio-server pull request #378
Opened 2024-09-23 05:48 UTC by orgads

2024-09-23 15:18 UTC, davehorton requested changes
This was clearly not tested with a local hiredis install.  In my testing if fails to build.

```
/usr/bin/ld: /home/runner/work/drachtio-server/drachtio-server/build/../src/blacklist.cpp:216: undefined reference to `redisFree'
/usr/bin/ld: src/drachtio-blacklist.o: in function `drachtio::QuerySentinel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, boost::asio::ip::basic_endpoint<boost::asio::ip::tcp> const&, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)':
/home/runner/work/drachtio-server/drachtio-server/build/../src/blacklist.cpp:76: undefined reference to `redisConnect'
```

2024-09-23 15:21 UTC, orgads commented
It was tested on docker. I'll test it further.

2024-09-23 18:08 UTC, orgads commented
Sorry, I cherry-picked it from my branch with the wrong base. Should be ok now.

2024-09-26 11:36 UTC, davehorton commented
@orgads 
just so I understand, is your intent for this PR that drachtio server **only** builds with system hiredis, or that it builds with either (system provided or deps provided)?

2024-09-26 11:38 UTC, orgads commented
Both work. The previous revision had `-d` instead of `-f` in the condition, so it failed when hiredis was not installed on the system. I corrected that.

2025-01-18 20:16 UTC, orgads commented
Rebased (based on "Improve docker" PR).

2026-09-14 10:38 UTC, closed without merging